[package]
name = "michiu"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true
description = "This is a facade for michiu, a GUI library for Windows."

[lints]
workspace = true

[dev-dependencies]
pollster = "1.0.1"

[dependencies]
michiu_ui = { workspace = true, optional = true }
michiu_guard = { workspace = true, optional = true }
michiu_window = { workspace = true, optional = true }

[dependencies.windows]
version = "0.62.2"
features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
]

[features]
default = ["ui", "guard", "window", "trace-error"]

ui = ["dep:michiu_ui"]
trace-error = ["michiu_ui?/trace-error"]
trace-lifecycle = ["trace-error"]
trace-entity = ["trace-lifecycle"]
snapshot = ["trace-error"]
webview2 = ["michiu_ui?/webview2", "trace-error"]
css = ["michiu_ui?/css", "trace-error"]

guard = ["dep:michiu_guard"]
window = ["dep:michiu_window"]

serde = [
    "michiu_ui?/serde",
    "michiu_guard?/serde",
    "michiu_window?/serde"
]


[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
default-target = "x86_64-pc-windows-msvc"
targets = ["x86_64-pc-windows-msvc"]
