[package]
name = "michiu"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "This is a facade for michiu, a GUI library for Windows."
readme = "README.md"

[dependencies]
michiu_ui = { workspace = true, optional = true }
michiu_guard = { workspace = true, optional = true }
michiu_window = { workspace = true, optional = true }

[features]
default = ["ui", "guard", "window"]
ui = ["dep:michiu_ui"]
guard = ["dep:michiu_guard"]
window = ["dep:michiu_window"]
serde = [
    "michiu_ui?/serde",
    "michiu_guard?/serde",
    "michiu_window?/serde"
]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
default-target = "x86_64-pc-windows-msvc"
targets = ["x86_64-pc-windows-msvc"]
